name: CI

on:
  push:
  pull_request:

jobs:
  find-duplicate-workflows:
    runs-on: [ self-hosted ]
    steps:
      - id: skip-check
        uses: paescuj/skip-duplicate-actions@debug
        with:
          concurrent_skipping: "same_content_newer"
          skip_after_successful_duplicate: "true"
      - uses: actions/checkout@v2
      - run: |
          git rev-parse HEAD
          ls
          echo "should_skip=${{ steps.skip-check.outputs.should_skip }}"

